### ISSUE TITLE
cursor in code editor barely visible

### ISSUE THREAD

**Issue by Matszwe02** [mainsail-crew/mainsail#1426] opened 2023-06-18 19:10 UTC
### Requested feature:

When I use arrow keys to move the cursor, it still blinks, making its position not always visible. Make its blink timer reset when arrow keys are pressed or suspend blinking when moving cursor.

### Solves the following problem:

cursor barely visible when moving through the code

**Comment by meteyou** [comment] 2023-06-18 19:21
This is a duplicate of #1331 and was fixed with #1200

**Closed by meteyou** 2023-06-18 19:21 UTC
Labels: 💡 Type: FR
