### ISSUE TITLE
Failed to update system packages 

### ISSUE THREAD

**Issue by kimprints** [mainsail-crew/mainsail#1093] opened 2022-09-19 19:11 UTC
### Mainsail Version:

2.3.1

### Browser:

Edge

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

update fails when trying to update system packages through the web UI
![image](https://user-images.githubusercontent.com/113939603/191096733-cfd7c6d7-9b08-4ec4-bb21-81421c45fef2.png)

### What did you expect to happen instead?

for the update to finish

### How to reproduce this bug?

click update on the mainsail update page/widget

**Comment by th33xitus** [comment] 2022-09-19 19:21
The error comes from your linux system and is very likely not caused by Mainsail.
You can try to manually update the system through SSH with the command line.
Assuming you have MainsailOS or another Debian based image installed, the command for that is
`sudo apt-get update && sudo apt-get upgrade -y`

**Comment by kimprints** [comment] 2022-09-19 19:40
i'll try that. I also read from an old post that this could've been caused when using sudo during the initial installation. In any case,  i'll try to update through the cmd line. thank you!

**Comment by th33xitus** [comment] 2022-09-19 19:42
Okay. Im going to close this issue for now. If you still need help or have questions, feel free to join our Discord server and we can help you there.

**Closed by th33xitus** 2022-09-19 19:42 UTC
Labels: ⚡ Type: Bug, ❔ User Input
