### ISSUE TITLE
hardcoded absolute URL paths everywhere

### ISSUE THREAD

**Issue by your-friend-alice** [mainsail-crew/mainsail#1357] opened 2023-04-27 04:20 UTC
### Mainsail Version:

2.5.1

### Browser:

Firefox

### Device:

Laptop

### Operating System:

Linux

### What happened?

the server hosting hosts other apps, so I have nginx configured to serve the app at `/mainsail`, instead of `/`. But this doesn't work, as throughout the HTML, JS, and CSS, there's hardcoded absolute paths assuming the app is hosted at `/`. I have this awful hack in my nginx config to make it temporarily sorta work:

```
location / {
  try_files $uri $uri/ /mainsail/$uri /mainsail/$uri/ =404;
}
```

but it's not great, and even with this ugly workaround, it's still not perfect, something in the JS is using the history API to overwrite the URL bar, resetting the path back to `/`.

Just one example of the problem, note the leading slash: https://github.com/mainsail-crew/mainsail/blob/370d7d414287bd12a1aa7ffa18a5c6ef4f746d4a/index.html#L22

### What did you expect to happen instead?

I expected the app to use relative URLs

### How to reproduce this bug?

Install mainsail to a subdirectory of nginx's root directory

**Comment by meteyou** [comment] 2023-04-27 05:00
Duplicate of https://github.com/mainsail-crew/mainsail/issues/1163

**Closed by meteyou** 2023-04-27 05:00 UTC
Labels: ⚡ Type: Bug
