### ISSUE TITLE
G-Code files favorites

### ISSUE THREAD

**Issue by HitLuca** [mainsail-crew/mainsail#1672] opened 2023-12-06 14:34 UTC
### Requested feature:

It would be nice to have a way to keep favorite gcode files to be always available on a dedicated section, or have a way to filter the files list to only show favorite gcodes.
This feature comes handy when printing a lot of different things, but having to go back to a handful of files to reprint (online shop objects, replacement parts etc.)

**Comment by meteyou** [comment] 2023-12-07 10:56
This is a duplicate of https://github.com/mainsail-crew/mainsail/issues/1623.

and for your second usecase, you can also use the job queue.

**Closed by meteyou** 2023-12-07 10:56 UTC
Labels: 💡 Type: FR
