### ISSUE TITLE
User Logins

### ISSUE THREAD

**Issue by ThePopeSays** [mainsail-crew/mainsail#1145] opened 2022-11-09 18:07 UTC
### Requested feature:

I'm attempting to implement utilizing Mainsail for dozens of printers in a university additive manufacturing lab, but would like to prevent students unfettered access to the underlying system and .cfg files.

So basically, having an admin login and a configurable everyone else login would be swell.

**Comment by meteyou** [comment] 2022-11-10 22:07
duplicate of #267

**Closed by meteyou** 2022-11-10 22:07 UTC
Labels: duplicate, 💡 Type: FR
