### ISSUE TITLE
Removing the first letter in the directory name when saving the configuration file.

### ISSUE THREAD

**Issue by gcastle2007** [mainsail-crew/mainsail#809] opened 2022-05-15 20:16 UTC
### Browser:

Firefox

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

I create the directory through the Mainsal interface named "macro".
I go to the "macro" directory and create the file name "line.cfg". I edit the file line.cfg. I press the save button. Mainsail tries to save the changes in the "acro/line.cfg" file, that is, losing the first letter in the directory name.

### What did you expect to happen instead?

Mainsail must be save in to path "macro/line.cfg".

### How to reproduce this bug?

I described everything at the very beginning.

### Additional information:

Screenshot:
https://cloud.mail.ru/public/nts7/LUCWn8ccD

**Comment by th33xitus** [comment] 2022-05-15 20:19
Duplicate of: https://github.com/mainsail-crew/mainsail/issues/801

And already fixed. Will be live with the next beta release.

**Closed by th33xitus** 2022-05-15 20:19 UTC
Labels: duplicate
