### ISSUE TITLE
GUI fan names

### ISSUE THREAD

**Issue by SargonofAssyria** [mainsail-crew/mainsail#2059] opened 2024-11-30 17:54 UTC
### Requested feature:

It would be nice if in the settings fan0, fan1, etc. could be given a name in the GUI like extruder fan, chamber fan, etc....
Or am I overlooking something?

**Comment by meteyou** [comment] 2024-11-30 19:54
duplicate of https://github.com/mainsail-crew/mainsail/issues/2005

**Closed by meteyou** 2024-11-30 19:54 UTC
Labels: 💡 Type: FR
