### ISSUE TITLE
Uneditable printer.cfg and no text populating in klicky-macros.cfg

### ISSUE THREAD

**Issue by Robbierob916** [mainsail-crew/mainsail#1444] opened 2023-06-25 18:53 UTC
### Mainsail Version:

v1.0.0-11-ge4976f6

### Browser:

Safari

### Device:

Desktop PC

### Operating System:

macOS

### What happened?

Updated Klipper, Mainsail and Moonraker and printer.cfg is no longer editable.  Also working on Klicky probe install and Klicky-macros.cfg will come up, but no text displayed.
<img width="1419" alt="Screenshot 2023-06-25 at 2 45 15 PM" src="https://github.com/mainsail-crew/mainsail/assets/121585339/ccd363f9-2cbc-437a-81ca-53af04323d3c">
<img width="1965" alt="Screenshot 2023-06-25 at 2 46 23 PM" src="https://github.com/mainsail-crew/mainsail/assets/121585339/f86ba568-90a0-4fe8-862a-7aa565c207c0">
<img width="1965" alt="Screenshot 2023-06-25 at 2 46 58 PM" src="https://github.com/mainsail-crew/mainsail/assets/121585339/eb3dcaf7-d4b3-4d5b-be85-13155a805e60">
<img width="1965" alt="Screenshot 2023-06-25 at 2 47 12 PM" src="https://github.com/mainsail-crew/mainsail/assets/121585339/425aa414-9d54-41a7-a511-2da041ab6309">

### What did you expect to happen instead?

File to be editable and visible

### How to reproduce this bug?

Not sure.  Was working fine yesterday, prior to updates of Klipper, Moonraker and Mainsail.  For my case, SW, set up, it happens every time, does not clear after reboot.  I am running a Laptop with 2 instances of Klipper, moon raker.  The other printer.cfg displays and edits fine.  I can also update the files and view them from the Host laptop.

**Comment by meteyou** [comment] 2023-06-25 21:46
duplicate of #1433

**Comment by meteyou** [comment] 2023-06-25 21:47
and i think your mainsail version in your bugreport is also wrong. i think you mean v2.6.0

**Comment by truckershitch** [comment] 2023-06-26 13:47
@Robbierob916 Can you post your `printer.cfg` and `klicky-macros.cfg`?

I would like to look at them further.

**Comment by meteyou** [comment] 2023-06-29 23:00
@Mcrcheli if you speak from desktop pcs/macs, the browser + version number would be much more important, than the OS. so pls post your browser name and version number of your browser

**Comment by Mcrcheli** [comment] 2023-06-30 00:10
web browser: Safari
Version 16.3 (18614.4.6.1.6)

**Comment by Robbierob916** [comment] 2023-06-30 01:02
@truckershitch ...Sorry, got busy at work...Thanks for the ask...I will post both files, but forewarning, printer.cfg is a bit of a mess, because I was in the middle of installing/troubleshooting Klicky probe and deciding on if I wanted it servo actuated.  I kept getting a Jinja parsing error, so I updated Klipper, Mainsail and Moonraker.  After update, no bueno.  

As far as the Klicky-Macros.cfg, I would assume it will show fine in the post as I can read it and edit it outside of Mainsail.  The problem with Klicky-macros.cfg is that when I open it in Mainsail nothing is visible.  


[printercfg.txt](https://github.com/mainsail-crew/mainsail/files/11911469/printercfg.txt)

[klicky-macroscfg.txt](https://github.com/mainsail-crew/mainsail/files/11911470/klicky-macroscfg.txt)

**Comment by meteyou** [comment] 2023-06-30 20:19
sry. i tested both files with a fresh installed mainsail v2.6.0 and safari 16.5 (i think this is the newest release) without any issues. another user posted the same issue on the discord server and a clear cache of his browser fixed the issue for him. pls test this on your system.

**Closed by meteyou** 2023-06-30 20:19 UTC
Labels: ⚡ Type: Bug, duplicate

**Comment by Robbierob916** [comment] 2023-06-30 22:04
Tests and results:
Mac mini: Safari 16.1, OS Ventura 13.0.1 - cleared Cache, no joy...
IMac: Safari 16.3, OS Monterey 12.6.5 (same issue) - cleared Cache, no joy...
Ipad OS 16.5.1, Safari Version??? - works, files visible and editable
Other tests:
Mac mini: OS Ventura 13.0.1, Google Chrome - works, files visible and editable
IMac: OS Monterey 12.6.5 Mac, Google Chrome - works, files visible and editable
Mac: Updated to Monterey 12.6.7, Safari 16.5 - cleared Cache, works, files visible and editable

Typing this on Mac mini, will try update and give feedback shortly...

Thanks for the help...

**Comment by Robbierob916** [comment] 2023-06-30 22:57
Final result, success... with update to MacOS 13.4.1 and Safari 16.5, clear cache - works and files are editable...

Thank you again

**Comment by meteyou** [comment] 2023-07-01 05:22
Thanks for all your tests! So it looks like a safari issue in older versions.
