### ISSUE TITLE
Remove error inducing text form autoedit code

### ISSUE THREAD

**Issue by Imforpeace** [mainsail-crew/mainsail#1122] opened 2022-10-16 07:30 UTC
### Requested feature:

Remove the automatic deletion of the decimal separator and zeros.
When editing a pressure advance value text form with an existing value of 0.03, The thought process would be to press on the text form(which causes the whole value to be selected), press right arrow to unselect all and go to the end of the value, press backspace, number 4, enter, and expect a value of 0.04s to be executed on the next move; instead, as soon as the last natural number is removed from the decimal section, all zeros as well as the decimal separator gets deleted automatically.

### Solves the following problem:

When editing text forms for years on end, and getting used to doing it fast, this catches you off guard and makes you press enter before realizing that instead of 0.04, the text form is set to 4 seconds and that your klipper is about to go into shutdown state.

### Additional information:

For a real example, see below.
https://imgur.com/a/BnufF0A

I have accidentally errored my printer because of this feature more times than I'd like to admit.

**Comment by th33xitus** [comment] 2022-10-16 10:03
Duplicate of: https://github.com/mainsail-crew/mainsail/issues/972

**Closed by th33xitus** 2022-10-16 10:03 UTC
Labels: duplicate
