### ISSUE TITLE
After the latest update, webcam is shown upside down

### ISSUE THREAD

**Issue by R4toLoko** [mainsail-crew/mainsail#1494] opened 2023-07-29 02:35 UTC
### Mainsail Version:

v2.6.1

### Browser:

Other (Please tell us below)
Brave and Firefox

### Device:

Desktop PC

### Operating System:

Linux

### What happened?

After the last update, well, I only updated everything last night, my webcam is upside down.
I have made no changes in my end, only the the updates.
I have those options enabled since day one because the cam is mounted upside down. 
It was never an issue.

![image](https://github.com/mainsail-crew/mainsail/assets/35049512/e903a1da-392f-453e-b7e1-e6e92f25da31)

![image](https://github.com/mainsail-crew/mainsail/assets/35049512/5253f1ad-c604-46df-9f5c-9f8d77a69140)

### What did you expect to happen instead?

The camera to be working as expected.

### How to reproduce this bug?

I just turned the printer on and the cam is upside down with no way to fix it.

**Comment by R4toLoko** [comment] 2023-07-29 02:39
That is weird, the timelapse looks correct

![image](https://github.com/mainsail-crew/mainsail/assets/35049512/b4d82832-4b4b-4fd9-9510-ef33486c9530)

**Comment by meteyou** [comment] 2023-07-29 08:02
Duplicate of https://github.com/mainsail-crew/mainsail/issues/1485 and already fixed. Plus check first, if there was already a bug report, before opening a new one!

**Closed by meteyou** 2023-07-29 08:02 UTC
Labels: ⚡ Type: Bug
