### ISSUE TITLE
Allow to start any print from queue not only first one

### ISSUE THREAD

**Issue by ristein** [mainsail-crew/mainsail#1379] opened 2023-05-06 10:17 UTC
### Mainsail Version:

2.5.1

### Browser:

Firefox

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

Having multiple files in queue but I can't use it as a todo-list because I can only start the job added first from queue screen.

### What did you expect to happen instead?

Should be possible to start any file from queue not having to go look for it in files tab

### How to reproduce this bug?

add two file to queue
try to start second one

**Comment by meteyou** [comment] 2023-05-06 19:06
Why should this be a bug?

**Comment by ristein** [comment] 2023-05-06 19:13
Why should this be intentional?

**Comment by th33xitus** [comment] 2023-05-06 19:23
> Why should this be intentional?

It's currently the intended behavior. Should this be rather a feature request instead?

**Comment by ristein** [comment] 2023-05-06 20:29
that would be great

**Comment by meteyou** [comment] 2024-02-03 19:25
fixed with the PR #1692

**Closed by meteyou** 2024-02-03 19:25 UTC
Labels: 💡 Type: FR
