### ISSUE TITLE
Printer name in browser tab during printing

### ISSUE THREAD

**Issue by ckvsoft** [mainsail-crew/mainsail#1322] opened 2023-03-24 11:07 UTC
### Requested feature:

It would be nice if the name of the printer remained in the tab when printing or was appended to the progress display in the tab.
With several printers this is annoying.

**Comment by mikebcbc** [comment] 2023-05-12 20:52
I made a PR that got merged that adds this. Once it's released i think this issue can be closed

**Comment by meteyou** [comment] 2023-05-12 23:10
normally i close the FR when i merge (automatically by github because the issue is linked in the PR)

**Closed by meteyou** 2023-05-12 23:10 UTC
Labels: 💡 Type: FR, good first issue

**Comment by mikebcbc** [comment] 2023-05-13 13:09
Cool!
